### ISSUE TITLE
error in the database fle

### ISSUE THREAD

**Issue by 0ur4n05** [rahulkhimsuriya/php_simple_blog#1]
Error
Static analysis:

3 errors were found during analysis.

A comma or a closing bracket was expected. (near "(" at position 289)
Unexpected beginning of statement. (near "`registered_at`" at position 295)
Unrecognized statement type. (near "date" at position 311)
SQL query:

CREATE TABLE `users` ( `id` int(10) UNSIGNED NOT NULL, `first_name` varchar(50) NOT NULL, `last_name` varchar(50) NOT NULL, `email` varchar(100) NOT NULL, `username` varchar(100) NOT NULL, `password` varchar(255) NOT NULL, `updated_at` date NOT NULL DEFAULT current_timestamp(), `registered_at` date NOT NULL DEFAULT current_timestamp() ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4

MySQL said: Documentation

#1067 - Invalid default value for 'updated_at'

**Comment by rahulkhimsuriya** [comment]
@0UR4N05 
# Thanks for your time.

- This is just fun project for me when I'm learning PHP. 😉
